<?php
declare(strict_types=1);
require dirname(__DIR__).'/config/bootstrap.php';
use AcquaVale\OrderService;
$service=new OrderService();$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){try{csrf_validate();$a=$_POST['action']??'';if($a==='create_order'){$o=$service->create($_POST,$_FILES['photos']??[]);redirect(url('index.php?order='.urlencode($o['order_code'])));}if($a==='simulate_payment'){$service->simulatePayment((int)($_POST['order_id']??0));redirect(url('index.php?order='.urlencode((string)($_POST['order_code']??''))));}}catch(Throwable $e){$error=$e->getMessage();}}
$order=!empty($_GET['order'])?$service->getOrderByCode((string)$_GET['order']):null;
$products=db()->query("SELECT * FROM products WHERE active=1 ORDER BY sort_order,id")->fetchAll();$meta=[];foreach($products as $p)$meta[(string)$p['id']]=['name'=>$p['name'],'price'=>(float)$p['price'],'requires_visitor'=>(bool)$p['requires_visitor']];
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ingressos | AcquaVale Park</title><meta name="description" content="Compre ingressos e adicionais para o AcquaVale Park."><link rel="stylesheet" href="assets/css/app.css"></head><body>
<header class="site-header"><div class="container nav"><a class="brand" href="./"><img src="https://www.acquavale.com.br/acquavale-logo.png" alt="AcquaVale"></a><div class="nav-actions"><a class="btn btn-outline" href="https://www.acquavale.com.br/">Conheça o parque</a><button class="btn btn-primary" id="checkout-section">Comprar ingressos</button></div></div></header>
<?php if($order):?>
<main><section class="hero" style="padding:54px 0 74px"><div class="container"><span class="eyebrow">Pedido <?=e($order['order_code'])?></span><h1 style="font-size:clamp(2.4rem,5vw,4.3rem)">Seu passeio está <span>quase pronto.</span></h1><p>Confira o resumo e conclua a simulação de pagamento. A integração real com adquirente/PIX entra na próxima etapa.</p></div></section><div class="wave"></div><section class="section"><div class="container checkout-shell"><div class="card panel"><h2 style="color:var(--navy);margin-top:0">Resumo do pedido</h2>
<?php foreach($order['items'] as $i):?><div class="summary-row"><span><?=(int)$i['quantity']?>× <?=e($i['product_name'])?></span><strong><?=money((float)$i['unit_price']*(int)$i['quantity'])?></strong></div><?php endforeach;?><div class="summary-row total"><span>Total</span><strong><?=money($order['total'])?></strong></div><p><span class="status <?=e($order['status'])?>"><?=e($order['status'])?></span></p>
<?php if($order['status']==='pending_payment'):?><div class="notice">Ambiente de simulação: nenhum valor será cobrado.</div><form method="post" style="margin-top:18px"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="simulate_payment"><input type="hidden" name="order_id" value="<?=(int)$order['id']?>"><input type="hidden" name="order_code" value="<?=e($order['order_code'])?>"><button class="btn btn-lime">Simular pagamento aprovado</button></form>
<?php else:?><div class="notice success"><strong>Pagamento simulado aprovado.</strong> A venda está persistida e liberada para integração/validação.</div><h3 style="color:var(--navy);margin-top:26px">Ingressos</h3><?php foreach($order['tickets'] as $t):?><div class="visitor-card"><strong><?=e($t['first_name'].' '.$t['last_name'])?></strong><p style="margin:7px 0"><?=e($t['product_name'])?> · <?=e(date('d/m/Y',strtotime($t['valid_from'])))?> a <?=e(date('d/m/Y',strtotime($t['valid_to'])))?></p><div class="ticket-code"><?=e($t['ticket_code'])?></div></div><?php endforeach;?><?php endif;?></div>
<aside class="card panel sticky"><span class="pill">AcquaVale</span><h3 style="font-size:1.5rem;color:var(--navy)">Dados da compra</h3><p><strong>E-mail:</strong><br><?=e($order['buyer_email'])?></p><p><strong>Telefone:</strong><br><?=e($order['buyer_phone'])?></p><a class="btn btn-outline" href="./" style="width:100%">Nova compra</a></aside></div></section></main>
<?php else:?>
<main><section class="hero"><div class="container hero-grid"><div><span class="eyebrow">Ingressos oficiais AcquaVale</span><h1>Seu dia de <span>diversão</span> começa aqui.</h1><p>Escolha seus ingressos, cadastre os visitantes e deixe tudo pronto antes de chegar ao parque.</p><button class="btn btn-lime" onclick="document.getElementById('ingressos').scrollIntoView({behavior:'smooth'})">Escolher ingressos</button></div><div class="hero-card"><strong>Compra rápida e entrada preparada</strong><ul><li>Ingressos de 1 ou mais dias</li><li>Adicionais como locker</li><li>Foto preparada para identificação facial</li><li>Resumo completo antes do pagamento</li></ul></div></div></section><div class="wave"></div>
<section class="section" id="ingressos"><div class="container"><div class="section-title"><div><span class="pill">Escolha sua experiência</span><h2>Ingressos e adicionais</h2></div><p>Valores, NCM, CEST, duração e regras ficam administráveis no painel.</p></div><?php if($error):?><div class="notice error" style="margin-bottom:22px"><?=e($error)?></div><?php endif;?><div class="products"><?php foreach($products as $p):?><article class="card product-card"><span class="pill"><?=e($p['product_type']==='ticket'?$p['duration_days'].' dia(s)':'Adicional')?></span><h3><?=e($p['name'])?></h3><p><?=e($p['description'])?></p><div class="price"><?=money($p['price'])?></div><div class="qty"><button type="button" data-qty-action="minus" data-product="<?=(int)$p['id']?>">−</button><input type="number" min="0" max="20" value="0" data-product-id="<?=(int)$p['id']?>"><button type="button" data-qty-action="plus" data-product="<?=(int)$p['id']?>">+</button></div></article><?php endforeach;?></div></div></section>
<section class="section" id="checkout" style="padding-top:20px"><div class="container"><div class="section-title"><div><span class="pill">Checkout</span><h2>Dados da compra</h2></div><p>Para cada ingresso, cadastre a pessoa que utilizará o acesso.</p></div><form method="post" enctype="multipart/form-data" class="checkout-shell"><section class="card panel"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="create_order"><input type="hidden" name="cart" id="cart-json" value="{}"><h3 style="color:var(--navy);margin-top:0">Contato do comprador</h3><div class="form-grid" style="margin-bottom:24px"><div class="form-group"><label>E-mail</label><input type="email" name="buyer_email" required autocomplete="email"></div><div class="form-group"><label>Telefone</label><input name="buyer_phone" required autocomplete="tel"></div></div><h3 style="color:var(--navy)">Visitantes</h3><div class="notice">A foto fica fora da pasta pública e preparada para futura integração com reconhecimento facial nas catracas.</div><div id="visitors" style="margin-top:16px"></div><div class="notice" style="margin-top:20px">Ao continuar, você verá o resumo antes da simulação de pagamento.</div><button class="btn btn-primary" type="submit" style="margin-top:18px">Revisar e criar pedido</button></section><aside class="card panel sticky"><span class="pill">Seu pedido</span><div id="cart-summary" style="margin-top:16px"></div><div class="summary-row total"><span>Total</span><strong id="cart-total">R$ 0,00</strong></div><p style="color:var(--muted);font-size:.9rem">Pagamento ainda em modo de simulação.</p></aside></form></div></section></main><script>window.AQV_PRODUCTS=<?=json_encode($meta,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;</script><script src="assets/js/app.js"></script>
<?php endif;?><footer class="footer"><div class="container footer-grid"><img src="https://www.acquavale.com.br/acquavale-logo.png" alt="AcquaVale"><div>AcquaVale Park · Serra da Mantiqueira<br><small>Venda online preparada para integração de pagamento e catracas.</small></div></div></footer></body></html>
